import { StyleSheet } from 'react-native'

const SURFACE_CARD_STYLE = { borderWidth: 1, borderColor: '#d5dfef', borderRadius: 14, backgroundColor: '#ffffff' }
const MODAL_PANEL_STYLE = { borderWidth: 1, borderColor: '#d5dfef', borderRadius: 16, backgroundColor: '#ffffff' }
const OUTLINED_BUTTON_STYLE = { borderWidth: 1, borderRadius: 11, paddingHorizontal: 12, paddingVertical: 9 }

export const styles = StyleSheet.create({
  authShell: {
    flex: 1,
    backgroundColor: '#0b1232',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  authCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#334d9f',
    borderRadius: 14,
    backgroundColor: '#131f4a',
    paddingHorizontal: 14,
    paddingVertical: 16,
    gap: 10,
  },
  authTitle: {
    color: '#f3f7ff',
    fontSize: 20,
    fontWeight: '800',
  },
  authSubtitle: {
    color: '#c8d7ff',
    fontSize: 13,
    lineHeight: 19,
  },
  authMessage: {
    color: '#ffd5de',
    fontSize: 12,
    fontWeight: '600',
  },
  authCaption: {
    color: '#9fb6ff',
    fontSize: 11,
  },
  authInput: {
    borderWidth: 1,
    borderColor: '#4d67b6',
    borderRadius: 10,
    backgroundColor: '#f6f8ff',
    color: '#1b2a59',
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 13,
    fontWeight: '600',
  },
  authDividerText: {
    color: '#9fb6ff',
    fontSize: 12,
    textAlign: 'center',
    fontWeight: '700',
  },
  authButtonPrimary: {
    backgroundColor: '#3d65ef',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  authButtonSecondary: {
    backgroundColor: '#203063',
    borderColor: '#3c5ec7',
    borderWidth: 1,
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
  },
  authButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '700',
  },
  authButtonSecondaryText: {
    color: '#d9e5ff',
    fontSize: 13,
    fontWeight: '700',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#0b1232',
  },
  shell: {
    flex: 1,
    position: 'relative',
  },
  contentPane: {
    flex: 1,
    backgroundColor: '#f4f7fc',
  },
  scrollContent: {
    paddingHorizontal: 14,
    paddingVertical: 16,
    paddingBottom: 40,
    gap: 8,
  },
  scrollContentPictures: {
    flexGrow: 1,
  },
  picturesScreenScroll: {
    flex: 1,
  },
  topBarCard: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    borderColor: '#d3deee',
    borderWidth: 1,
    padding: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    shadowColor: '#1c2d4f',
    shadowOpacity: 0.07,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 8,
    elevation: 2,
  },
  topBarLeftGroup: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    flexShrink: 1,
  },
  menuButton: {
    width: 34,
    height: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#cfdaeb',
    backgroundColor: '#f7faff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  menuIconWrap: {
    gap: 3,
  },
  menuLine: {
    width: 14,
    height: 2,
    borderRadius: 2,
    backgroundColor: '#4d638f',
  },
  topBarSyncText: {
    color: '#334a74',
    fontWeight: '700',
    flexShrink: 1,
  },
  refreshButton: {
    backgroundColor: '#1f4fd5',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 8,
    minWidth: 95,
    alignItems: 'center',
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  refreshButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  loadingBox: {
    backgroundColor: '#f9fbff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#cdd8f5',
    paddingVertical: 14,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  inlineLoadingBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  loadingText: {
    color: '#445889',
  },
  errorBox: {
    marginBottom: 8,
    backgroundColor: '#ffe8ec',
    borderColor: '#ee9db0',
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  errorText: {
    color: '#8e233f',
    fontWeight: '500',
  },
  sectionTitle: {
    marginTop: 10,
    fontSize: 21,
    fontWeight: '800',
    color: '#112447',
    marginBottom: 6,
  },
  sectionSubtitle: {
    color: '#4b618d',
    marginBottom: 6,
  },
  unreadSummaryBox: {
    marginTop: 8,
    marginBottom: 4,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#f0c66d',
    backgroundColor: '#fff8e8',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  unreadSummaryText: {
    color: '#6d4b11',
    fontSize: 13,
    fontWeight: '700',
  },
  timesheetCard: {
    marginTop: 8,
    ...SURFACE_CARD_STYLE,
    padding: 12,
    gap: 8,
  },
  timesheetWorkerText: {
    color: '#1b2a59',
    fontSize: 12,
    fontWeight: '700',
  },
  timesheetDateButton: {
    borderWidth: 1,
    borderColor: '#c8d6ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingVertical: 10,
    gap: 2,
  },
  timesheetDateButtonText: {
    color: '#1b2a59',
    fontWeight: '700',
    fontSize: 13,
  },
  timesheetDateHint: {
    color: '#536895',
    fontSize: 11,
  },
  timesheetDatePickerWrap: {
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  timesheetStagePickerWrap: {
    borderWidth: 1,
    borderColor: '#c8d6ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    overflow: 'hidden',
  },
  timesheetStagePicker: {
    color: '#1b2a59',
  },
  timesheetInlineHint: {
    color: '#6b7fa8',
    fontSize: 12,
  },
  timesheetNotesInput: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  timesheetMessage: {
    color: '#204fc2',
    fontSize: 12,
    fontWeight: '600',
  },
  timesheetListTitle: {
    color: '#1b2a59',
    fontSize: 14,
    fontWeight: '700',
  },
  timesheetList: {
    gap: 8,
    marginTop: 6,
  },
  timesheetEntryRow: {
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  managerSheetCard: {
    marginTop: 8,
    ...SURFACE_CARD_STYLE,
    padding: 12,
    gap: 10,
  },
  managerCalendarHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  managerCalendarNavButton: {
    borderWidth: 1,
    borderColor: '#c7d5ff',
    borderRadius: 8,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  managerCalendarNavButtonText: {
    color: '#29479f',
    fontSize: 12,
    fontWeight: '700',
  },
  managerCalendarMonthLabel: {
    color: '#1b2a59',
    fontSize: 14,
    fontWeight: '800',
    textTransform: 'capitalize',
  },
  managerCalendarWeekRow: {
    flexDirection: 'row',
    marginTop: 2,
  },
  managerCalendarWeekdayLabel: {
    width: '14.2857%',
    textAlign: 'center',
    color: '#60719b',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  managerCalendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    borderWidth: 1,
    borderColor: '#d6e1ff',
    borderRadius: 10,
    backgroundColor: '#f5f8ff',
    overflow: 'hidden',
  },
  managerCalendarBlankCell: {
    width: '14.2857%',
    aspectRatio: 1,
    borderWidth: 0.5,
    borderColor: '#e3eafe',
    backgroundColor: '#f5f8ff',
  },
  managerCalendarDayCell: {
    width: '14.2857%',
    aspectRatio: 1,
    borderWidth: 0.5,
    borderColor: '#e3eafe',
    backgroundColor: '#e8efff',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
  },
  managerCalendarDayCellPressed: {
    backgroundColor: '#d9e4ff',
  },
  managerCalendarDayCellDisabled: {
    backgroundColor: '#ffffff',
  },
  managerCalendarDayCellSelected: {
    backgroundColor: '#2d57cc',
    borderColor: '#1f429e',
  },
  managerCalendarDayLabel: {
    color: '#1d3165',
    fontSize: 13,
    fontWeight: '700',
  },
  managerCalendarDayLabelDisabled: {
    color: '#b6c3e4',
  },
  managerCalendarDayLabelSelected: {
    color: '#ffffff',
  },
  managerCalendarMissingBubble: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 7,
    height: 7,
    borderRadius: 999,
    backgroundColor: '#cc2f45',
  },
  managerCalendarLegend: {
    color: '#576d9c',
    fontSize: 11,
    lineHeight: 15,
  },
  managerCalendarEmptyText: {
    color: '#8a4a59',
    fontSize: 12,
    fontWeight: '600',
  },
  managerProgressList: {
    gap: 8,
  },
  managerProgressRow: {
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 4,
  },
  managerProgressJob: {
    color: '#1b2a59',
    fontSize: 13,
    fontWeight: '800',
  },
  managerProgressMeta: {
    color: '#536895',
    fontSize: 12,
  },
  managerProgressInput: {
    borderWidth: 1,
    borderColor: '#c8d6ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    color: '#1b2a59',
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontWeight: '700',
  },
  managerSheetMessage: {
    color: '#204fc2',
    fontSize: 12,
    fontWeight: '600',
  },
  alertsCard: {
    marginTop: 8,
    ...SURFACE_CARD_STYLE,
    padding: 12,
    gap: 8,
  },
  alertsList: {
    gap: 8,
  },
  alertRow: {
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 4,
  },
  alertRowUnread: {
    borderColor: '#9fb7ff',
    backgroundColor: '#f4f8ff',
  },
  alertHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  alertUnreadBadge: {
    borderRadius: 999,
    backgroundColor: '#d73b5d',
    paddingHorizontal: 8,
    paddingVertical: 2,
  },
  alertUnreadBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  alertTitle: {
    color: '#1b2a59',
    fontWeight: '800',
    fontSize: 13,
    flex: 1,
  },
  alertBody: {
    color: '#425485',
    fontSize: 12,
  },
  alertMeta: {
    color: '#5a6f99',
    fontSize: 11,
    fontWeight: '600',
  },
  alertTapHint: {
    color: '#4f6292',
    fontSize: 11,
    fontWeight: '500',
  },
  alertMessage: {
    color: '#204fc2',
    fontSize: 12,
    fontWeight: '600',
  },
  settingsPageHero: {
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#99adef',
    borderRadius: 14,
    backgroundColor: '#dee7ff',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 6,
  },
  settingsPageTitle: {
    color: '#1a2550',
    fontSize: 22,
    fontWeight: '800',
  },
  settingsPageSubtitle: {
    color: '#3d4f82',
    fontSize: 13,
    lineHeight: 18,
  },
  settingsMetaRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  settingsMetaChip: {
    borderWidth: 1,
    borderColor: '#8ea4ea',
    backgroundColor: '#ffffff',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  settingsMetaChipText: {
    color: '#223f8f',
    fontSize: 12,
    fontWeight: '700',
  },
  settingsMenuCard: {
    marginTop: 12,
    ...SURFACE_CARD_STYLE,
    padding: 8,
    gap: 8,
  },
  settingsMenuRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    borderWidth: 1,
    borderColor: '#d2dcff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  settingsMenuRowPressed: {
    borderColor: '#9fb7ff',
    backgroundColor: '#edf2ff',
  },
  settingsMenuTextBlock: {
    flex: 1,
    gap: 2,
  },
  settingsMenuTitle: {
    color: '#1a2550',
    fontSize: 15,
    fontWeight: '800',
  },
  settingsMenuSubtitle: {
    color: '#4e6294',
    fontSize: 12,
  },
  settingsMenuMetaBlock: {
    alignItems: 'flex-end',
    gap: 2,
  },
  settingsMenuStatus: {
    color: '#32529d',
    fontSize: 11,
    fontWeight: '700',
  },
  settingsMenuChevron: {
    color: '#2749a1',
    fontSize: 16,
    fontWeight: '800',
    lineHeight: 16,
  },
  settingsTitle: {
    color: '#1a2550',
    fontSize: 16,
    fontWeight: '800',
  },
  settingsSubtitle: {
    color: '#4e6294',
    fontSize: 13,
    lineHeight: 18,
  },
  settingsToggleButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#203063',
    borderColor: '#3c5ec7',
    ...OUTLINED_BUTTON_STYLE,
  },
  settingsToggleButtonSecondary: {
    backgroundColor: '#3756b5',
  },
  settingsActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  settingsToggleButtonText: {
    color: '#d9e5ff',
    fontSize: 13,
    fontWeight: '700',
  },
  settingsLanguageRow: {
    flexDirection: 'row',
    gap: 8,
  },
  settingsLanguageButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#c6d2f8',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingVertical: 10,
    alignItems: 'center',
  },
  settingsLanguageButtonActive: {
    borderColor: '#3c5ec7',
    backgroundColor: '#e8eeff',
  },
  settingsLanguageButtonText: {
    color: '#22366f',
    fontSize: 13,
    fontWeight: '700',
  },
  settingsUpdateMessage: {
    color: '#204fc2',
    fontSize: 12,
    fontWeight: '600',
  },
  settingsInlineStatus: {
    color: '#34559f',
    fontSize: 12,
    fontWeight: '600',
  },
  settingsDangerButton: {
    alignSelf: 'flex-start',
    borderColor: '#9d4a63',
    backgroundColor: '#512037',
    ...OUTLINED_BUTTON_STYLE,
  },
  settingsDangerButtonText: {
    color: '#ffdbe5',
    fontSize: 13,
    fontWeight: '700',
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  metricCard: {
    width: '48%',
    borderRadius: 12,
    borderWidth: 1,
    minHeight: 116,
    paddingVertical: 12,
    paddingHorizontal: 12,
    shadowColor: '#1a2345',
    shadowOpacity: 0.09,
    shadowOffset: { width: 0, height: 3 },
    shadowRadius: 8,
    elevation: 2,
  },
  metricCardPressed: {
    transform: [{ scale: 0.985 }],
  },
  metricLabel: {
    fontSize: 12,
    fontWeight: '600',
  },
  metricValue: {
    marginTop: 4,
    fontWeight: '800',
    fontSize: 24,
  },
  metricHelper: {
    marginTop: 4,
    fontSize: 11,
  },
  metricActionText: {
    marginTop: 6,
    fontSize: 11,
    color: '#1a2550',
    fontWeight: '700',
  },
  detailHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  detailTitle: {
    color: '#1a2550',
    fontWeight: '800',
    fontSize: 17,
    flexShrink: 1,
  },
  detailCloseButton: {
    backgroundColor: '#273c84',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  detailCloseButtonText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '700',
  },
  detailRow: {
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 2,
  },
  detailPrimary: {
    color: '#1b2a59',
    fontWeight: '700',
    fontSize: 13,
  },
  detailSecondary: {
    color: '#536895',
    fontSize: 12,
  },
  orderDetailActionButton: {
    borderWidth: 1,
    borderColor: '#2f5ad4',
    backgroundColor: '#1f4fd5',
    borderRadius: 11,
    paddingHorizontal: 12,
    paddingVertical: 10,
    alignSelf: 'flex-start',
  },
  orderDetailActionButtonDisabled: {
    opacity: 0.55,
  },
  orderDetailActionButtonText: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  orderDetailMessage: {
    color: '#2e4f9e',
    fontSize: 12,
    fontWeight: '600',
  },
  emptyDetailText: {
    color: '#5a6f99',
    fontSize: 13,
  },
  emptyPicturesBox: {
    ...SURFACE_CARD_STYLE,
    padding: 12,
  },
  ordersListCard: {
    ...SURFACE_CARD_STYLE,
    padding: 12,
    gap: 10,
  },
  orderSearchInput: {
    borderWidth: 1,
    borderColor: '#c8d6ff',
    borderRadius: 10,
    backgroundColor: '#ffffff',
    color: '#1b2a59',
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontWeight: '600',
  },
  ordersListScroll: {
    flex: 1,
  },
  ordersListContent: {
    gap: 8,
    paddingBottom: 8,
  },
  orderListItem: {
    borderWidth: 1,
    borderColor: '#d3deee',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundColor: '#fdfefe',
    gap: 6,
  },
  orderListItemPressed: {
    borderColor: '#9fb4d8',
    backgroundColor: '#f3f7ff',
  },
  orderListTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  orderListIdBadge: {
    borderWidth: 1,
    borderColor: '#bfd0ea',
    backgroundColor: '#edf3ff',
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  orderListIdText: {
    color: '#23406f',
    fontSize: 11,
    fontWeight: '800',
  },
  orderListStatusPill: {
    color: '#3f547f',
    fontSize: 11,
    fontWeight: '700',
    maxWidth: '70%',
  },
  orderListName: {
    color: '#22366f',
    fontSize: 13,
    fontWeight: '700',
  },
  orderListMeta: {
    color: '#4e6294',
    fontSize: 12,
    fontWeight: '600',
  },
  orderProgressRow: {
    marginTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  orderProgressLabel: {
    color: '#2a477f',
    fontSize: 11,
    fontWeight: '700',
    flex: 1,
  },
  orderProgressWorkersMeta: {
    color: '#4e6294',
    fontSize: 11,
    fontWeight: '600',
    maxWidth: '52%',
    textAlign: 'right',
  },
  orderProgressTrack: {
    marginTop: 2,
    borderRadius: 999,
    height: 6,
    backgroundColor: '#e3ebfc',
    overflow: 'hidden',
  },
  orderProgressFill: {
    height: '100%',
    borderRadius: 999,
    backgroundColor: '#2c62df',
  },
  orderProgressMeta: {
    color: '#657aa6',
    fontSize: 10,
    fontWeight: '600',
  },
  ordersPaginationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 10,
  },
  ordersPaginationButton: {
    minWidth: 88,
    borderWidth: 1,
    borderColor: '#bad0fb',
    borderRadius: 10,
    backgroundColor: '#edf3ff',
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  ordersPaginationButtonText: {
    color: '#244a8e',
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  ordersPaginationMeta: {
    flex: 1,
    textAlign: 'center',
    color: '#3d5386',
    fontSize: 12,
    fontWeight: '700',
  },
  pictureOrderTextBlock: {
    flex: 1,
    gap: 1,
  },
  pictureOrderMeta: {
    color: '#4e6294',
    fontSize: 12,
  },
  takePictureButton: {
    backgroundColor: '#204fc2',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  takePictureButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  uploadQueueButton: {
    backgroundColor: '#1f5f40',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  uploadQueueButtonText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 12,
  },
  clearQueueButton: {
    borderWidth: 1,
    borderColor: '#6f7fbe',
    backgroundColor: '#ffffff',
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  clearQueueButtonText: {
    color: '#2b3f85',
    fontWeight: '700',
    fontSize: 12,
  },
  pictureMessage: {
    color: '#204fc2',
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 6,
  },
  pictureModalActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-start',
    marginTop: 4,
  },
  pendingQueueCard: {
    borderWidth: 1,
    borderColor: '#cad7ff',
    borderRadius: 10,
    backgroundColor: '#f3f7ff',
    paddingHorizontal: 10,
    paddingVertical: 8,
    gap: 6,
    marginBottom: 4,
  },
  pendingQueueTitle: {
    color: '#213b80',
    fontSize: 12,
    fontWeight: '800',
  },
  pendingQueueHint: {
    color: '#536894',
    fontSize: 12,
  },
  pendingQueueGrid: {
    gap: 8,
    paddingRight: 4,
  },
  pendingQueueItem: {
    width: 82,
    alignItems: 'center',
    gap: 4,
  },
  pendingQueueImage: {
    width: 78,
    height: 78,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#bfd0ff',
    backgroundColor: '#dbe6ff',
  },
  pendingQueueRemoveButton: {
    position: 'absolute',
    top: -4,
    right: -2,
    width: 20,
    height: 20,
    borderRadius: 999,
    backgroundColor: '#6a2f49',
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingQueueRemoveButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '800',
  },
  pendingQueueItemLabel: {
    color: '#4f6395',
    fontSize: 11,
    fontWeight: '600',
  },
  photoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 2,
  },
  photoTile: {
    width: '48%',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d9e3ff',
    borderRadius: 10,
    overflow: 'hidden',
  },
  photoImage: {
    width: '100%',
    aspectRatio: 1,
    backgroundColor: '#e2e8ff',
  },
  photoTileCaption: {
    paddingHorizontal: 8,
    paddingVertical: 6,
    color: '#4b6191',
    fontWeight: '600',
    fontSize: 11,
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(8, 16, 46, 0.46)',
    paddingHorizontal: 14,
    justifyContent: 'center',
  },
  modalCard: {
    maxHeight: '82%',
    ...MODAL_PANEL_STYLE,
    padding: 12,
    gap: 10,
  },
  confirmCard: {
    ...MODAL_PANEL_STYLE,
    padding: 14,
    gap: 10,
  },
  confirmTitle: {
    color: '#1a2550',
    fontSize: 18,
    fontWeight: '800',
  },
  confirmText: {
    color: '#4e6294',
    fontSize: 13,
    lineHeight: 18,
  },
  confirmActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
    marginTop: 2,
  },
  confirmCancelButton: {
    borderColor: '#c6d2f8',
    backgroundColor: '#ffffff',
    ...OUTLINED_BUTTON_STYLE,
  },
  confirmCancelButtonText: {
    color: '#38508a',
    fontSize: 12,
    fontWeight: '700',
  },
  confirmDangerButton: {
    borderColor: '#9d4a63',
    backgroundColor: '#512037',
    ...OUTLINED_BUTTON_STYLE,
  },
  confirmDangerButtonText: {
    color: '#ffdbe5',
    fontSize: 12,
    fontWeight: '700',
  },
  modalBodyContent: {
    gap: 8,
    paddingBottom: 8,
  },
  sidebarScrim: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(11, 18, 50, 0.28)',
  },
  sidebarDrawer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    width: 220,
    backgroundColor: '#101836',
    borderRightWidth: 1,
    borderRightColor: '#1f2a56',
    paddingTop: 46,
    paddingHorizontal: 10,
  },
  sidebarBrandBox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
    gap: 8,
  },
  sidebarBrandA: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: '#3c62f0',
    color: '#ffffff',
    textAlign: 'center',
    textAlignVertical: 'center',
    fontSize: 16,
    fontWeight: '800',
    overflow: 'hidden',
  },
  sidebarBrandText: {
    color: '#ced8ff',
    fontSize: 18,
    fontWeight: '700',
  },
  sidebarNav: {
    gap: 10,
  },
  sidebarActions: {
    marginTop: 18,
    gap: 10,
  },
  sidebarItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#2a376f',
    backgroundColor: '#16224a',
  },
  sidebarItemActive: {
    borderColor: '#7fa2ff',
    backgroundColor: '#2a3f8e',
  },
  sidebarItemShort: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: '#0f1739',
    color: '#c8d4ff',
    fontWeight: '700',
    textAlign: 'center',
    textAlignVertical: 'center',
    overflow: 'hidden',
  },
  sidebarItemLabelRow: {
    marginLeft: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sidebarItemLabel: {
    color: '#d2dcff',
    fontWeight: '600',
  },
  sidebarAlertBadge: {
    minWidth: 18,
    borderRadius: 999,
    backgroundColor: '#d73b5d',
    paddingHorizontal: 6,
    paddingVertical: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sidebarAlertBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '800',
  },
  sidebarSignOutButton: {
    borderWidth: 1,
    borderColor: '#9d4a63',
    borderRadius: 10,
    backgroundColor: '#512037',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  sidebarSignOutText: {
    color: '#ffdbe5',
    fontWeight: '700',
    fontSize: 12,
  },
})
