import { lazy } from 'react'

export const AppLayout = lazy(() => import('../layout/AppLayout'))
export const DashboardPage = lazy(() => import('../pages/DashboardPage'))
export const TimesheetPage = lazy(() => import('../pages/TimesheetPage'))
export const SupportPage = lazy(() => import('../pages/SupportPage'))
export const PicturesPage = lazy(() => import('../pages/PicturesPage.tsx'))
export const OrdersPage = lazy(() => import('../pages/OrdersPage'))
export const TemplatesPage = lazy(() => import('../pages/TemplatesPage'))
export const VisitorsPage = lazy(() => import('../pages/VisitorsPage'))
export const AdminUsersPage = lazy(() => import('../pages/AdminUsersPage'))
export const AdminAlertsPage = lazy(() => import('../pages/AdminAlertsPage'))
export const AdminApiPage = lazy(() => import('../pages/AdminApiPage'))
export const AdminSalesReviewPage = lazy(() => import('../pages/AdminSalesReviewPage'))
export const AdminLogsPage = lazy(() => import('../pages/AdminLogsPage'))
export const CrmDealersPage = lazy(() => import('../pages/CrmDealersPage'))
export const CrmContactsPage = lazy(() => import('../pages/CrmContactsPage'))
export const AiConfigPage = lazy(() => import('../pages/AiConfigPage'))
export const AdminSettingsPage = lazy(() => import('../pages/AdminSettingsPage'))
export const SalesPage = lazy(() => import('../pages/SalesPage'))
export const PurchasingPage = lazy(() => import('../pages/PurchasingPage'))
export const OperatingCostsPage = lazy(() => import('../pages/OperatingCostsPage'))
